require('dotenv').config();
const express=require('express');const cors=require('cors');const helmet=require('helmet');const rateLimit=require('express-rate-limit');const bcrypt=require('bcryptjs');const jwt=require('jsonwebtoken');const path=require('path');const {Pool}=require('pg');
const app=express();const port=Number(process.env.PORT||3000);const secret=process.env.JWT_SECRET;
if(!secret||secret.length<32){console.warn('JWT_SECRET devrait contenir au moins 32 caractères.');}
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false,max:10,idleTimeoutMillis:30000});
app.set('trust proxy',1);app.use(helmet({contentSecurityPolicy:false}));app.use(cors({origin:process.env.CORS_ORIGIN||true}));app.use(express.json({limit:'1mb'}));app.use(express.static(path.join(__dirname,'public')));
const limiter=rateLimit({windowMs:15*60*1000,limit:300,standardHeaders:true,legacyHeaders:false});app.use('/api',limiter);const authLimiter=rateLimit({windowMs:15*60*1000,limit:20});
const safeUser=u=>({id:u.id,firstName:u.first_name,lastName:u.last_name,email:u.email,role:u.role,level:u.level,objective:u.objective,subscription:u.subscription,xp:u.xp});
const token=u=>jwt.sign({id:u.id,role:u.role},secret,{expiresIn:'7d'});
async function auth(req,res,next){try{const h=req.get('authorization')||'';if(!h.startsWith('Bearer '))throw Error();req.user=jwt.verify(h.slice(7),secret);next();}catch{res.status(401).json({success:false,message:'Session invalide'});}}
function admin(req,res,next){return req.user?.role==='admin'?next():res.status(403).json({success:false,message:'Accès administrateur requis'});}
function email(v){return String(v||'').trim().toLowerCase();}
app.get('/api/health',async(req,res)=>{try{await pool.query('SELECT 1');res.json({success:true,status:'ok'});}catch{res.status(503).json({success:false,status:'database_unavailable'});}});
app.post('/api/auth/register',authLimiter,async(req,res)=>{try{const firstName=String(req.body.firstName||'').trim(),lastName=String(req.body.lastName||'').trim(),mail=email(req.body.email),password=String(req.body.password||'');if(firstName.length<2||!/^\S+@\S+\.\S+$/.test(mail)||password.length<8)return res.status(400).json({success:false,message:'Prénom, email valide et mot de passe de 8 caractères requis.'});const hash=await bcrypt.hash(password,12);const r=await pool.query(`INSERT INTO users(first_name,last_name,email,password_hash) VALUES($1,$2,$3,$4) RETURNING *`,[firstName,lastName,mail,hash]);res.status(201).json({success:true,token:token(r.rows[0]),user:safeUser(r.rows[0])});}catch(e){res.status(e.code==='23505'?409:500).json({success:false,message:e.code==='23505'?'Email déjà utilisé':'Erreur serveur'});}});
app.post('/api/auth/login',authLimiter,async(req,res)=>{try{const r=await pool.query('SELECT * FROM users WHERE email=$1',[email(req.body.email)]);if(!r.rows[0]||!(await bcrypt.compare(String(req.body.password||''),r.rows[0].password_hash)))return res.status(401).json({success:false,message:'Email ou mot de passe incorrect'});res.json({success:true,token:token(r.rows[0]),user:safeUser(r.rows[0])});}catch{res.status(500).json({success:false,message:'Erreur serveur'});}});
app.get('/api/me',auth,async(req,res)=>{const r=await pool.query('SELECT * FROM users WHERE id=$1',[req.user.id]);if(!r.rows[0])return res.status(404).json({success:false});res.json({success:true,user:safeUser(r.rows[0])});});
app.put('/api/me',auth,async(req,res)=>{const r=await pool.query(`UPDATE users SET first_name=COALESCE(NULLIF($1,''),first_name),last_name=COALESCE($2,last_name),level=COALESCE($3,level),objective=COALESCE($4,objective),updated_at=NOW() WHERE id=$5 RETURNING *`,[String(req.body.firstName||''),req.body.lastName,req.body.level,req.body.objective,req.user.id]);res.json({success:true,user:safeUser(r.rows[0])});});
app.get('/api/courses',auth,async(req,res)=>{const r=await pool.query(`SELECT c.*,COUNT(l.id)::int AS lesson_count FROM courses c LEFT JOIN lessons l ON l.course_id=c.id AND l.published=true WHERE c.published=true GROUP BY c.id ORDER BY c.id`);res.json({success:true,courses:r.rows});});
app.get('/api/courses/:id',auth,async(req,res)=>{const c=await pool.query('SELECT * FROM courses WHERE id=$1 AND published=true',[req.params.id]);if(!c.rows[0])return res.status(404).json({success:false});const l=await pool.query('SELECT id,title,description,lesson_number,duration FROM lessons WHERE course_id=$1 AND published=true ORDER BY lesson_number',[req.params.id]);res.json({success:true,course:{...c.rows[0],lessons:l.rows}});});
app.get('/api/lessons/:id',auth,async(req,res)=>{const r=await pool.query('SELECT l.*,c.title course_title FROM lessons l JOIN courses c ON c.id=l.course_id WHERE l.id=$1 AND l.published=true',[req.params.id]);if(!r.rows[0])return res.status(404).json({success:false});res.json({success:true,lesson:r.rows[0]});});
app.post('/api/progress',auth,async(req,res)=>{const id=Number(req.body.lessonId);if(!Number.isInteger(id))return res.status(400).json({success:false,message:'Leçon invalide'});await pool.query(`INSERT INTO lesson_progress(user_id,lesson_id,completed,completed_at) VALUES($1,$2,$3,CASE WHEN $3 THEN NOW() ELSE NULL END) ON CONFLICT(user_id,lesson_id) DO UPDATE SET completed=EXCLUDED.completed,completed_at=EXCLUDED.completed_at,updated_at=NOW()`,[req.user.id,id,Boolean(req.body.completed)]);if(req.body.completed)await pool.query('UPDATE users SET xp=xp+10,updated_at=NOW() WHERE id=$1',[req.user.id]);res.json({success:true});});
app.get('/api/progress',auth,async(req,res)=>{const r=await pool.query('SELECT lesson_id,completed FROM lesson_progress WHERE user_id=$1',[req.user.id]);res.json({success:true,progress:r.rows});});
app.get('/api/exercises',auth,async(req,res)=>{const r=await pool.query('SELECT id,title,question,options,explanation,xp FROM exercises WHERE published=true ORDER BY id');res.json({success:true,exercises:r.rows});});
app.get('/api/quizzes',auth,async(req,res)=>{const r=await pool.query('SELECT id,title,description,level,duration,xp FROM quizzes WHERE published=true ORDER BY id');res.json({success:true,quizzes:r.rows});});
app.get('/api/admin/stats',auth,admin,async(req,res)=>{const [u,c,q]=await Promise.all([pool.query("SELECT COUNT(*)::int count FROM users WHERE role='student'"),pool.query('SELECT COUNT(*)::int count FROM courses'),pool.query('SELECT COUNT(*)::int count FROM quizzes')]);res.json({success:true,students:u.rows[0].count,courses:c.rows[0].count,quizzes:q.rows[0].count});});
app.get('/api/admin/users',auth,admin,async(req,res)=>{const r=await pool.query('SELECT id,first_name,last_name,email,role,level,subscription,xp,created_at FROM users ORDER BY created_at DESC');res.json({success:true,users:r.rows});});
app.use((req,res,next)=>{if(req.method==='GET'&&!req.path.startsWith('/api'))return res.sendFile(path.join(__dirname,'public','index.html'));next();});
(async()=>{try{await pool.query('SELECT 1');const e=email(process.env.ADMIN_EMAIL);if(e&&process.env.ADMIN_PASSWORD){const found=await pool.query('SELECT id FROM users WHERE email=$1',[e]);if(!found.rows[0]){const h=await bcrypt.hash(process.env.ADMIN_PASSWORD,12);await pool.query(`INSERT INTO users(first_name,last_name,email,password_hash,role,subscription,level) VALUES('Admin','EL PROF',$1,$2,'admin','premium','Bac')`,[e,h]);}}app.listen(port,()=>console.log(`EL PROF sur http://localhost:${port}`));}catch(err){console.error(err);process.exit(1);}})();
